#!sh
# Colour Themes:
focused_border_colour    : #fabd2f
unfocused_border_colour  : #555555
swap_border_colour       : #c0cbff

# General Options:
gaps                    : 10
border_width            : 1
master_width            : 60
resize_master_amount    : 1
resize_stack_amount		: 20
snap_distance           : 5
motion_throttle         : 144
should_float            : "Thunar", "filezilla", "obs", "sxiv", "pcmanfm", "xarchiver", "spotify"
new_win_focus			: true
warp_cursor				: true

# Keybinds:
mod_key : super

# Application Launchers:
bind : mod + Return : "st"
bind : mod + shift + Return : "alacritty"
bind : mod + b : "firefox"
# bind : mod + p : "dmenu_run_config"
# bind : mod + shift + s : "screenshot"
bind : mod + p : "sh -c 'dmenu_run -fn '\''terminus:bold:pixelsize=18'\'' -nb '\''#211d1d'\'' -nf '\''#d5c4a1'\'' -sb '\''#fabd2f'\'' -sf '\''#211d1d'\'' -p '\''Run:'\'''"
bind : mod + shift + s : "sh -c 'mkdir -p ~/Pictures/screenshots && maim -s -u ~/Pictures/screenshots/$(date +%F_%H-%M).png | xclip -selection clipboard -t image/png -i'"
bind : mod + f : "Thunar"
bind : mod + w : "wallpaper_next"

bind : mod + i : "res_1920x1080"
bind : mod + o : "res_1380x1080"

# Window Management:
call : mod + shift + q : close_window
call : mod + shift + e : quit

# Focus Movement:
call : mod + j : focus_next
call : mod + k : focus_prev

# Master/Stack Movement
call : mod + shift + j : master_next
call : mod + shift + k : master_previous

# Master Area Resize
call : mod + l : master_increase
call : mod + h : master_decrease
call : mod + n : stack_increase
call : mod + m : stack_decrease

# Gaps 
call : mod + equal : increase_gaps
call : mod + minus : decrease_gaps

# Floating/Fullscreen
call : mod + space : toggle_floating
call : mod + shift + space : global_floating
call : mod + shift + f : fullscreen

# Reload Config
call : mod + r : reload_config

# Workspaces (1-9)
workspace : mod + 1          : move 1
workspace : mod + shift + 1  : swap 1
workspace : mod + 2          : move 2
workspace : mod + shift + 2  : swap 2
workspace : mod + 3          : move 3
workspace : mod + shift + 3  : swap 3
workspace : mod + 4          : move 4
workspace : mod + shift + 4  : swap 4
workspace : mod + 5          : move 5
workspace : mod + shift + 5  : swap 5
workspace : mod + 6          : move 6
workspace : mod + shift + 6  : swap 6
workspace : mod + 7          : move 7
workspace : mod + shift + 7  : swap 7
workspace : mod + 8          : move 8
workspace : mod + shift + 8  : swap 8
workspace : mod + 9          : move 9
workspace : mod + shift + 9  : swap 9
