#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config active_border_color \#ffa35c
bspc config normal_border_color \#cf844a

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart Applications
sxhkd &
dunst &
picom &
xrandr --output DP-0 --mode 1920x1080 --rate 144.00 &
feh --bg-scale ~/.wallpapers/my-neighbor-totoro-sunflowers.png &
~/.config/polybar/blocks/launch.sh &
